name: pixela

on:
  push:
    branches:
    - actions

jobs:
  increment:
    runs-on: ubuntu-18.04
    steps:
    - users: actions/checkout@v1

    - name: increment
      uses: peaceiris/actions-pixela@v1
      env:
        PIXELA_USER_TOKEN: ${{ secrets.PIXELA_USER_TOKEN }}
      with:
        args: pixel increment -u m3y -g gopl
